name: GH-Pages
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          poetry install 
      - name: Build Documenations
        run: |
          poetry run python -m nox -s build
          touch styleguide/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: ./styleguide/_build/html
          git-config-name: Nicola Coretti
          git-config-email: nicola.coretti@exasol.com

